Repository MorganBergen/clarity, pull requests merged in 2024-10, with the labels that each got.

#18 added installation info for issue 17
  README.md
Labels: documentation

#23 converted array variables into strings to fix object initialization
  client/src/components/Questionnaire.js
Labels: bug

#25 24 update medical conditions answer options on questionnaire
  client/src/components/Questionnaire.js
Labels: documentation

#29 27 image upload and db save
  client/src/components/Logging.js
Labels: enhancement

#33 32 refactor code base
  client/src/App.js
  client/src/components/ApiTest.js
  client/src/components/Questionnaire.js
  server/app.js
  server/routes/api.js
  server/server.js
Labels: enhancement

#38 logout button fixed
  client/src/components/Questionnaire.js
Labels: bug

#42 20 missing forgot password link on loginjs
  client/src/components/Login.css
  client/src/components/Login.js
  client/src/components/Register.js
Labels: bug
